### ISSUE TITLE
'future' dependency update

### ISSUE THREAD

**Issue by GreenSmile** [open-pay/openpay-python#10]
Hi,

As far as I can see openpay library specifically requires version `0.15.2` of "future" package that was released back in 2015.
https://pypi.org/project/future/#history

There were several newer version released for this library since that time. Now I'm trying to solve dependency conflict in my project with openpay and several other packages requesting different "future" versions.

Could you please update openpay not to require specific version of "future" but accept `0.15.2`, `0.16.0`, `0.17.0` and `0.17.1`?

**Comment by jemy-dasm-openpay** [comment]
We are closing this issue because there have been many updates since it was opened.

Hopefully you're not having this issue anymore but if there are problems still happening please let us know and we'll open it again.

Cheers!
