### ISSUE TITLE
Create charges for stores

### ISSUE THREAD

**Issue by emiLosso** [open-pay/openpay-python#11]
Hola, quiero consultar sobre cómo realizar pagos en tiendas. Según el flujo entiendo que primero el cliente debe seleccionar una tienda (cuál es el método o en todo caso endpoint para obtener las tiendas?) y luego crear un "charge" de tipo "store" . Ahora cómo se asocia la tienda seleccionada al store? Gracias.

**Comment by letops** [comment]
Que tal Emi,

Perdona, hace muchísimo tiempo que no toco este proyecto. Sinceramente te recomendaría utilizar algo más como Stripe (con la librería de djstripe), ya que acaban de activarla para México. Por tu pregunta supongo que requieres hacer un marketplace, por lo que Stripe Connect sería perfecto para lo que necesitas.

La razón por la que te recomiendo esto es porque:
1. Llevo más de 6 meses intentando hacer que Openpay modifique las póliticas de "antifraude" que tienen para mi proyecto, ya que Openpay bloquea las tarjetas constantemente por lo que terminamos perdiendo clientes constantemente
2. La API de Openpay está mal escrita y llevo dos año solicitando cambios, al grado de que me recibieron en las oficinas para hablar de esto y no les interesa actualizar
3. Hay fallas en los webhooks desde hace año y medio, por lo que el flujo de información se puede romper (el webhook a veces no te manda el id del pago por lo que no tienes como relacionar la información)

**Comment by darkaz** [comment]
Hola @emiLosso 

Es correcto, debes crear una transacción de cargo de tipo tienda, esto te va a generar un referencia que puede pagar en cualquiera de nuestra red de tiendas. No es necesario seleccionar una tienda.
