### ISSUE TITLE
Como generar device_session_id 

### ISSUE THREAD

**Issue by jvaldezch** [open-pay/openpay-python#15]
Hola, estoy creando un API interno para manejar los cobros usando OpenPay vía Python, pero no queda claro como generar el device_session_id desde un backend.

gracias.

**Comment by oswaldopenpay** [comment]
Que tal @jvaldezch, por definición el device session id se genera de lado del navegador, se tienen otros esquemas de integración en caso que no se disponga de un navegador en la integración, si es tu caso puedes solicitar apoyo a soporte@openpay.mx

**Comment by jvaldezch** [comment]
Hare el contacto vía Email, gracias.
