### ISSUE TITLE
agregar tarjeta al customer mediante token 

### ISSUE THREAD

**Issue by bcapetillo** [open-pay/openpay-python#17]
**hola buen dia** , viendo la documentación no veo la manera en la cual se pueda agregar la tarjeta a un customer mediante el token de la tarjeta esto para el registro de tarjeta mediante dispositivos moviles. podrian proporcionarme un ejemplo de como hacerlo, o actualizar su documentación para estos casos en php lo realice mediante un add  pero este ejemplo similar no lo veo aqui .  Ya que estoy usando python como servicio web para mis aplicaciones.
![Captura de Pantalla 2020-12-03 a la(s) 11 34 05](https://user-images.githubusercontent.com/39779442/101065989-75d32500-355b-11eb-9b57-31f9a90be7f9.png)

**Comment by luismedina216** [comment]
![Screen Shot 2021-01-04 at 15 27 31](https://user-images.githubusercontent.com/19696850/103581343-6f5d0380-4ea1-11eb-8f37-84da597f37c9.png)

Para vincular la tarjeta con el cliente debes realizar esta acción desde la propiedad **Card**
 
card = openpay.Card.create( 

  customer = customer_id,
  
  token_id = token,
  
  device_session_id = session

)

Espero aún te sirva!
