### ISSUE TITLE
Problems detected

### ISSUE THREAD

**Issue by letops** [open-pay/openpay-python#3]
Hi there!! I am sorry for bothering you, but I have been using your library for a while and I have detected multiple problems and details. I'll just write you a list of the problems I have detected in hopes that you (or maybe another contributor) can read it and use it.

General
-----------
*   There is no method to create a `device_session_id` to execute some actions. Apparently the concept of `device_session_id` was introduced thanks to the [javascript]() version of this project and this python library was never updated to use the SJCL library for an antifraud feature.

Charges
-----------
-   The `create` function does not longer work like in the examples. It now requires another parameter: `device_session_id`.
-   The `capture` function does not longer work. The API replies with a **1005** code error. I do not know what the real problem is, but if I had to guess, it would be that while in Sandbox mode the API does not search for the transactions as expected. (No documentation text supports this idea)
-   The `refund` function has an error due to a `del` out of place (instead of being in line 439 it should be right after the 436 inside the `if` clause). A work around is to always send the boolean parameter **merchant**
-   The `refund` function is having the exact same problem as the `capture` function (described two bullets up)

**Comment by hiigami** [comment]
On the refund issue I think it should be like this:
``` 
def refund(self, **params):
        if 'merchant' in list(params.keys()):
            self._as_merchant = True
            del params['merchant']
        else:
            self._as_merchant = False
        url = self.instance_url() + '/refund'
        self.refresh_from(self.request('post', url, params))
        return self
```

and it also needs a change on line 420 to something like:
`if hasattr(self, '_as_merchant') and self._as_merchant == True:`

so that it can work on the sandbox env using the client url:
POST https://sandbox-api.openpay.mx/v1/{MERCHANT_ID}/customers/{CUSTOMER_ID}/charges/{TRANSACTION_ID}/refund

PD: I yet have to try it on production.

**Comment by letops** [comment]
Hey @hiigami :
I made all the required changes at our own [fork](https://github.com/grvty-labs/openpay-python), because we saw that there was no reply in this repo. We also have been fixing some other minor bugs as we find them. You can use our fork as you please, (although we have only tested it in python3), and install it with `pip install OpenpayGrvty`.

**Comment by hiigami** [comment]
Hi @letops,

Thanks for the invite, I gladly accept. I'll try to contribute as much as I can.
And I'll switch my to your fork.

**Comment by yusjacobs** [comment]
Hi @ @letops,

I've been struggling with the same issues you mentioned. Specifically with the create function in charges. I checked out your fork but it seem the documentation is the same. Have you solved the issues you mentioned?

**Comment by letops** [comment]
Hi @yusjacobs 
Sorry I didn't reply sooner. We actually fixed the third point in charges and some others that are not related to this list. The only problem is that due to the lack of interest and the horrible documentation from openpay, we moved on to elixir and made another library for them.

You can use our library, but the problem is that the version that it is published is not the latest one. If you want, you can use it as a submodule or give me a couple of hours to upgrade the pip version so you can use it.

If I may be sincere, I am not too fond of this library, just because it hasn't been properly updated through the years by openpay, the same goes to their documentation, but we are not gonna risk it with another provider... and they know it

**Comment by jemy-dasm-openpay** [comment]
We are closing this issue because there has been many updates since it was open.

If there are problems still happening please let us know and we can reopen this issue.

Cheers!
