### ISSUE TITLE
Refund method

### ISSUE THREAD

**Issue by jimlu10** [open-pay/openpay-python#4]
There is a problem in the refund method, as the parameter "merchant" is optional, the line 439 in resources.py is trying to delete the key even if there is no a parameter with that name.

- del params['merchant']

So, I had to always sent the "merchant" as a parameter to avoid the error, making the refund always as merchant=True.

Comparing with the function "capture", that line must be inside the previous if

Cheers.
![seleccion_170](https://cloud.githubusercontent.com/assets/24614848/21509973/1714909a-cc54-11e6-8d84-a4ca2f3dc67c.png)

**Comment by jemy-dasm-openpay** [comment]
We are closing this issue because there have been many updates since it was opened.

If there are problems still happening please let us know and we'll open this issue again.

Cheers!
