### ISSUE TITLE
Bad endpoint when creating charges

### ISSUE THREAD

**Issue by cserra10** [open-pay/openpay-python#5]
Hi.

As official docs refer, you can create a charge on 
1. "/{MERCHANT_ID}/charges"
or 
2. "/{MERCHANT_ID}/customers/{CUSTOMER_ID}/charges"

When you send the "customer" parameter to the create method of the charge resource, the URL must be the first one, not the second one.

Error here:
        if params and 'customer' in list(params.keys()):
            return "/v1/{0}/customers/{1}/{2}s".format(
                merchant_id, params.get('customer'), cls_name)
        else:
            return "/v1/%s/%ss" % (merchant_id, cls_name)

Fix:
        if params and 'customer' in list(params.keys()):
            return "/v1/%s/%ss" % (merchant_id, cls_name)
        else:
            return "/v1/{0}/customers/{1}/{2}s".format(
                merchant_id, params.get('customer'), cls_name)

**Comment by jemy-dasm-openpay** [comment]
We are closing this issue because there have been many updates since it was opened.

If there are problems still happening please let us know and we'll open this issue again.

Cheers!
